/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dms;

/**
 *
 * @author Uzair
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddNewProject = new javax.swing.JButton();
        AllocateTeam = new javax.swing.JButton();
        EditVolunteer = new javax.swing.JButton();
        AddDonor = new javax.swing.JButton();
        AddApplicant = new javax.swing.JButton();
        SearchProject = new javax.swing.JButton();
        SearchDonor = new javax.swing.JButton();
        SearchBeneficary = new javax.swing.JButton();
        AddDonation = new javax.swing.JButton();
        ShortListApplicant = new javax.swing.JButton();
        ViewProjectApplicant = new javax.swing.JButton();
        ViewProjectDonor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Donation Management System");

        AddNewProject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddNewProject.setText("Add New Project");
        AddNewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewProjectActionPerformed(evt);
            }
        });

        AllocateTeam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AllocateTeam.setText("Allocate Team");
        AllocateTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllocateTeamActionPerformed(evt);
            }
        });

        EditVolunteer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditVolunteer.setText("Edit Volunteer");
        EditVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditVolunteerActionPerformed(evt);
            }
        });

        AddDonor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddDonor.setText("Add Donor");
        AddDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDonorActionPerformed(evt);
            }
        });

        AddApplicant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddApplicant.setText("Add Applicant");
        AddApplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddApplicantActionPerformed(evt);
            }
        });

        SearchProject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchProject.setText("Search Project");
        SearchProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchProjectActionPerformed(evt);
            }
        });

        SearchDonor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchDonor.setText("Search Donor");
        SearchDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDonorActionPerformed(evt);
            }
        });

        SearchBeneficary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchBeneficary.setText("Search Applicant");
        SearchBeneficary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBeneficaryActionPerformed(evt);
            }
        });

        AddDonation.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AddDonation.setText("Add Donation");
        AddDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDonationActionPerformed(evt);
            }
        });

        ShortListApplicant.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ShortListApplicant.setText("Short List Applicant");
        ShortListApplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShortListApplicantActionPerformed(evt);
            }
        });

        ViewProjectApplicant.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ViewProjectApplicant.setText("View Project Applicant");
        ViewProjectApplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProjectApplicantActionPerformed(evt);
            }
        });

        ViewProjectDonor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ViewProjectDonor.setText("View Project Donor");
        ViewProjectDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProjectDonorActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Issue Donation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Add Pledge");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("View Pledge");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchProject, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(AddNewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditVolunteer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddApplicant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AllocateTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ViewProjectApplicant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchBeneficary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddDonation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ShortListApplicant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewProjectDonor, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(283, 283, 283))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddNewProject, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewProjectDonor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(SearchProject, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShortListApplicant, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ViewProjectApplicant, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(AllocateTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchDonor, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(EditVolunteer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SearchBeneficary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddDonation, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(AddApplicant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewProjectActionPerformed
        // TODO add your handling code here:
        AddNewProjectForm ANPF= new AddNewProjectForm();
        ANPF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddNewProjectActionPerformed

    private void AllocateTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllocateTeamActionPerformed
        // TODO add your handling code here:
        AllocateTeamForm ATF = new AllocateTeamForm();
        ATF.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_AllocateTeamActionPerformed

    private void EditVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditVolunteerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EditVolunteerForm EVF= new EditVolunteerForm();
        EVF.setVisible(true);
    }//GEN-LAST:event_EditVolunteerActionPerformed

    private void AddDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDonorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddDonorForm AD= new AddDonorForm();
        AD.setVisible(true);
    }//GEN-LAST:event_AddDonorActionPerformed

    private void AddApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddApplicantActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddApplicantForm AAF = new AddApplicantForm();
        AAF.setVisible(true);
    }//GEN-LAST:event_AddApplicantActionPerformed

    private void SearchProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchProjectActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SearchProjectForm spf= new SearchProjectForm();
        spf.setVisible(true);
        
    }//GEN-LAST:event_SearchProjectActionPerformed

    private void AddDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDonationActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddDonorContinueForm().setVisible(true);
    }//GEN-LAST:event_AddDonationActionPerformed

    private void ShortListApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShortListApplicantActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ShortListApplicant().setVisible(true);
        
    }//GEN-LAST:event_ShortListApplicantActionPerformed

    private void ViewProjectDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProjectDonorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewProjectDonor().setVisible(true);
        
    }//GEN-LAST:event_ViewProjectDonorActionPerformed

    private void ViewProjectApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProjectApplicantActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewProjectApplicant().setVisible(true);
    }//GEN-LAST:event_ViewProjectApplicantActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new IssueDonation().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDonorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SearchDonor().setVisible(true);
    }//GEN-LAST:event_SearchDonorActionPerformed

    private void SearchBeneficaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBeneficaryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SearchApplicant().setVisible(true);
    }//GEN-LAST:event_SearchBeneficaryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddPledge().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewPledge().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddApplicant;
    private javax.swing.JButton AddDonation;
    private javax.swing.JButton AddDonor;
    private javax.swing.JButton AddNewProject;
    private javax.swing.JButton AllocateTeam;
    private javax.swing.JButton EditVolunteer;
    private javax.swing.JButton SearchBeneficary;
    private javax.swing.JButton SearchDonor;
    private javax.swing.JButton SearchProject;
    private javax.swing.JButton ShortListApplicant;
    private javax.swing.JButton ViewProjectApplicant;
    private javax.swing.JButton ViewProjectDonor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
